### PR TITLE
HttpClient wasn't getting the parent span, breaking the trace

### PR DESCRIPTION
**Pull request by SilverXXX**
When using HttpClient a new trace were always generated, making a correct trace impossible

### CODE REVIEW

**Comment by cwe1ss** [comment]
That seems like a bug with your tracer. Even when using `Start()` the tracer should look for a `tracer.ActiveSpan` (unless `spanBuilder.IgnoreActiveSpan()` was called explicitly). Which tracer are you using?

I'm trying to avoid calling `StartActive()` if it's not necessary as using `AsyncLocal` (which is used by the underlying OpenTracing ScopeManager) has some overhead.

**Comment by cwe1ss** [comment]
Small addition: Making the "span" active isn't necessary here because there can't be any user code between the Start & Finish of this span as custom handlers are executed before this instrumentation is invoked. Also, luckily, `HttpRequestMessage` contains this `Properties` dictionary so we have a nice way to store the span in an existing construct. The tracer now only has to use `AsyncLocal` once to check for an existing parent when the span is created.

**Comment by SilverXXX** [comment]
I'm currently using [https://github.com/Chatham/LetsTrace](url) 
Judging from here [http://static.javadoc.io/io.opentracing/opentracing-api/0.30.0/io/opentracing/Tracer.SpanBuilder.html#startActive--](url) and here [https://github.com/opentracing/specification/issues/80#issuecomment-314795825](url) it seems only StartActive infer a childOf reference

**Comment by cwe1ss** [comment]
This is a bug in LetsTrace. The handling of "active spans" (via the new `Scope manager`) has been completely rewritten in Java 0.31.0 so your links reference the "old behavior". 

I created an issue in the LetsTrace repo: https://github.com/Chatham/LetsTrace/issues/12

I'm therefore closing this PR. Thanks anyway for testing this library and for finding this bug!! It's still early days for OpenTracing in C# so anyone willing to go through these initial pain points is greatly appreciated! 👍

**Pull request closed without merging**
