### PR TITLE
Upgrade to .net core 3

### PR DESCRIPTION
**Pull request by raz-canva**
Upgrade to .NET Core 3
Add support for endpoint routing

---

Update samples to .NET Core 3
Update all Nuget packages

### CODE REVIEW

**Comment by raz-canva** [comment]
Ping

**Comment by austinlparker** [comment]
This would break support for Net Core 2.x, right? We still have a lot of people using that. In addition, OpenTelemetry .NET will support Net Core 3 out of the box. What's your use case for this change?

**Comment by raz-canva** [comment]
My use case is for the endpoint-routing support added:
src/OpenTracing.Contrib.NetCore/AspNetCore/MvcEventProcessor.cs

In my application (without this change), when using endpoint routing, the URLS are not resolved and the metrics all show empty routes. 

Perhaps there is a way to incorporate this support without breaking .NET Core 2 support

**Comment by tcfialho** [comment]
People that still use Net Core 2.x can still using old opentracing-contrib version.

**Comment by razfriman** [comment]
Bump!!

**Comment by razfriman** [comment]
Bump again

**Comment by olucafont6** [comment]
Would be interested in this upgrade as well.

**Comment by cwe1ss** [comment]
As described in my other commit, I'm now multi-targeting .NET Core 2.1 and .NET Core 3.1, so most of this PR is now obsolete. Please create a separate PR for your changes regarding the endpoint routing logic if you still need that.

Thank you again for your time and sorry for ghosting you for such a long time.

**Pull request closed without merging**
