### PR TITLE
Resolves #27 too much logs write by GenericEventProcessor, add option…

### LINKED ISSUE #27: too much logs write by GenericEventProcessor, add options to ignore some
A action get request as following:

```csharp
        // GET api/values
        [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            using (var db = new DataContext())
            {
                db.Database.EnsureCreated();
                var user = new User
                {
                    Name = "hello",
                };
                db.Add(user);
                db.SaveChanges();

                var users = db.Users.ToArray();
            }

            return new string[] { "value1", "value2" };
        }
```
producuced 113 logs

```
Logs (113)
17.67ms:event=Route matched with {RouteData}. Executing action {ActionName}ActionName=TimeService.Controllers.ValuesController.Get (TimeService)RouteData={action = "Get", controller = "Values"}component=Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvokereventId=1level=Informationmessage=Route matched with {action = "Get", controller = "Values"}. Executing action TimeService.Controllers.ValuesController.Get (TimeService)
17.69ms:event=Microsoft.AspNetCore.Mvc.BeforeOnResourceExecutingcomponent=Microsoft.AspNetCore
17.72ms:event=Microsoft.AspNetCore.Mvc.AfterOnResourceExecutingcomponent=Microsoft.AspNetCore
17.75ms:event=Microsoft.AspNetCore.Mvc.BeforeOnActionExecutingcomponent=Microsoft.AspNetCore
17.75ms:event=Microsoft.AspNetCore.Mvc.AfterOnActionExecutingcomponent=Microsoft.AspNetCore
17.76ms:event=Microsoft.AspNetCore.Mvc.BeforeOnActionExecutingcomponent=Microsoft.AspNetCore
17.76ms:event=Microsoft.AspNetCore.Mvc.AfterOnActionExecutingcomponent=Microsoft.AspNetCore
...
```

most of the log are not concerned, and store them waste lots of disk, such as
```
45.24ms:event=Microsoft.EntityFrameworkCore.Database.Connection.ConnectionOpenedarg=Opened connection to database 'main' on server 'E:\Users\Chris\Desktop\tech\opentracing\jaeger\apps\JaegerTest\TimeService\data.sqlite'.component=Microsoft.EntityFrameworkCore
45.92ms:event=Microsoft.EntityFrameworkCore.Database.Transaction.TransactionStartedarg=Beginning transaction with isolation level 'Serializable'.component=Microsoft.EntityFrameworkCore
50.67ms:event=Microsoft.EntityFrameworkCore.ChangeTracking.ForeignKeyChangeDetectedarg=Foreign key property 'User.Id' detected as changed. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see property values.component=Microsoft.EntityFrameworkCore
50.73ms:event=Microsoft.EntityFrameworkCore.Database.Command.DataReaderDisposingarg=A data reader was disposed.component=Microsoft.EntityFrameworkCore
```

so I suggest add options for GenericEventProcessor so that we can ignore some or all the Generic Event.

### PR DESCRIPTION
**Pull request by chrishaly**
Resolves #27 too much logs write by GenericEventProcessor, add options to ignore some logs

### CODE REVIEW

**Comment by rwkarg** [comment]
I like this flexibility. Is there an idea of the performance impact of this, both for performing filtering as well as any impact with the new code but not doing any filtering?

**Comment by austinlparker** [comment]
This seems fine and I haven't seen any more comments around it, so I'm going to go ahead and merge it. Thanks for the contribution!

**Comment by trondhindenes** [comment]
would be possible to publish a new nuget release based on this? We're eagerly awaiting this :-)

**Comment by austinlparker** [comment]
Will try - I don't have permissions to deploy in AppVeyor it seems. I've made an issue (#43) to track the release process.

**Comment by trondhindenes** [comment]
awesome, thanks!

**Pull request merged**
