### PR TITLE
Resolves #48 Make the PropertyFetcher case insensitive

### LINKED ISSUE #48: The PropertyFetchers are not working with ASP.NET Core 3.0
The property fetchers in this section of the code (https://github.com/opentracing-contrib/csharp-netcore/blob/master/src/OpenTracing.Contrib.NetCore/AspNetCore/MvcEventProcessor.cs#L23-L26) don't work with ASP.NET Core 3.0, the `Fetch()` calls return `null`.

I'm not 100% sure of the reason, but probably it's that event argument types have changed in ASP.NET Core. For example in the `BeforeAction` event the `arg` is of [this type](https://github.com/aspnet/AspNetCore/blob/b23ea5b6683b08e8d168ccf49e0fc8515077ee2e/src/Mvc/Mvc.Core/src/Diagnostics/MvcDiagnostics.cs), in which the properties have upper case names (`HttpContext`, `ActionDescriptor`), but in the `PropertyFetcher`s we're trying to use lower case names (`httpContext`, `actionDescriptor`).  
If I change the strings there to start with upper case, then it starts working.

What should be the fix for this? I guess if I change the strings to uppercase, that fixes it for 3.0, but breaks it for 2.2. Would it be possible to make the `PropertyFetcher` ignore the case of the property name?

### PR DESCRIPTION
**Pull request by markvincze**
Details about the issue in #48 

Do I need to do anything else for the release (for example bumping the version, etc.), or everything else is taken care of by the CI build?

### CODE REVIEW

**Comment by austinlparker** [comment]
CI takes care of versioning when we make a release tag. Thanks for the fix!

**Comment by yelob** [comment]
Any timeline on getting a release that contains this fix?

**Comment by rwkarg** [comment]
Looks like release 0.6.1 was just created with this change in it!

**Comment by austinlparker** [comment]
It was! Happy Thursday. :)

**Comment by yelob** [comment]
Woo hoo! Thanks!

**Comment by yelob** [comment]
Thanks again for creating the release. At what point will that get pushed to nuget?

**Comment by austinlparker** [comment]
I published it a few minutes ago, so it should show up within the hour. Thanks for your patience!

**Comment by yelob** [comment]
Awesome, thanks again!

**Pull request merged**
